name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Load secrets from 1Password
      id: op-load
      uses: 1Password/load-secrets-action@v1.3.1
      with:
        export-env: true
      env: 
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        ROCKET_DATABASES: op://bbscorecard/db-user/envvar
    - name: print db
      run: echo "rocketurl $ROCKET_DATABASES"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
